namespace Application.Shared.Enumns;

public enum ErrorCode
{
    //Guest - 1 até 99
    GUEST_NOT_FOUND = 1,
    GUEST_COULDNOT_STORE_DATA = 2,
    GUEST_INVALID_EMAIL = 3,
    GUEST_INVALID_MIN_LENGTH = 4,
    GUEST_MISSING_REQUIRED = 5,
    GUEST_INVALID_PERSON_DOCUMENT = 6,
    GUEST_COULDNOT_GET_DATA = 2,

    //Room - 100 até 199
    ROOM_INVALID_MIN_LENGTH = 100,
    ROOM_MISSING_REQUIRED = 101,
    ROOM_INVALID_CURRENT_PRINCE = 102,
    ROOM_COULDNOT_STORE_DATA = 103,
    ROOM_NOT_FOUND = 104,
    ROOM_COULDNOT_GET_DATA = 105,

    //Booking - 200 até 299
    BOOKING_INVALID_PLACE_AT = 200,
    BOOKING_INVALID_START = 201,
    BOOKING_INVALID_END = 202,
    BOOKING_INVALID_GUEST = 203,
    BOOKING_INVALID_ROOM = 204,
    BOOKING_COULDNOT_STORE_DATA = 205,
    BOOKING_COULDNOT_GET_DATA = 206,
    BOOKING_NOT_FOUND = 207,
    BOOKING_CANNOT_BE_BOOKING = 208,

    //Payment - 300 até 399
    PAYMENT_INVALID_PAIMENT_INTENTION,

    //System
    GENERAL_ERROR = 999
}
