namespace Application.Shared.Enumns;

public enum ErrorCode
{
    //Guest - 1 até 99
    GUEST_NOT_FOUND = 1,
    GUEST_COULDNOT_STORE_DATA = 2,
    GUEST_INVALID_EMAIL = 3,
    GUEST_INVALID_MIN_LENGTH = 4,
    GUEST_MISSING_REQUIRED = 5,
    GUEST_INVALID_PERSON_DOCUMENT = 6,

    //Room - 100 até 199
    ROOM_INVALID_MIN_LENGTH = 100,
    ROOM_MISSING_REQUIRED = 101,
    ROOM_INVALID_CURRENT_PRINCE = 102,
    ROOM_COULDNOT_STORE_DATA = 103,
    ROOM_NOT_FOUND = 104
}
